sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    posts:
        permalink: docs/changelog/:year/:month/
        path: docs/changelog
        enabled: true

    docs:
        type: path
        path: _docs
        singular_name: doc
        enabled: true
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/:basename/

    guides:
        type: path
        path: docs/_guides
        singular_name: guide
        enabled: true
        taxonomies:
            - contributors
        permalink: docs/guides/:basename/
